[book]
authors = ["Ivan Begtin"]
language = "en"
multilingual = false
src = "src"
title = "Государственные НКО и их открытость"

[output.html]
git-repository-url = "https://github.com/ivbeg/book-govngo"